version: 4
shared:
  environment:
    PACKAGE_DIRECTORY: invirtualenv

jobs:
  validate_test:
    template: python/validate_unittest
    requires: [~commit, ~pr]

  validate_lint:
    template: python/validate_lint
    requires: [~commit, ~pr]

  validate_codestyle:
    template: python/validate_codestyle
    requires: [~commit, ~pr]

  validate_safetydb:
    template: python/validate_safety
    requires: [~commit, ~pr]
    
  validate_security:
    template: python/validate_security
    requires: [~commit, ~pr]
    
  generate_version:
    template: python/generate_version
    requires: [~commit]

  publish_test_pypi:
    template: python/package_python
    environment:
      PUBLISH: True
      TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
    requires: [validate_test, validate_lint, validate_codestyle, validate_safetydb, validate_security, generate_version]

  verify_test_package:
    template: python/validate_pypi_package
    environment:
        PYPI_INDEX_URL: https://test.pypi.org/simple
    requires: [publish_test_pypi]
  
  verify_rpm_package:
    template: python/package_rpm
    environment:
        PUBLISH: False
    steps:
        - postmotd: |
            cat > deploy.conf <<EOF
            [global]
            name = serviceping
            description = invirtualenv utility for deploying python applicatons
            version = 18.8.1
            link_bin_files = True
            virtualenv_dir = /var/lib/virtualenvs
            basepython=python3

            [pip]
            deps:
                serviceping==18.8.1

            [rpm_package]
            deps:
            EOF
        - postinstall_utility: |
            # Install the version from this repo instead of the invirtualenv from pypi
            $BASE_PYTHON -m pip install .
    requires: [verify_test_package]
  
  publish_prod_pypi:
    template: python/package_python
    environment:
      PUBLISH: True
    requires: [verify_rpm_package]
