version: 4
shared:
  environment:
    PACKAGE_DIRECTORY: invirtualenv

jobs:
  validate_test:
    template: python/validate_unittest
    requires: [~commit, ~pr]

  validate_lint:
    template: python/validate_lint
    requires: [~commit, ~pr]

  validate_codestyle:
    template: python/validate_codestyle
    requires: [~commit, ~pr]

  generate_version:
    template: python/generate_version
    requires: [~commit]

  publish_test_pypi:
    template: python/package_python
    environment:
      PUBLISH: True
      TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
    requires: [validate_test, validate_lint, validate_codestyle, generate_version]

  verify_test_package:
    template: python/validate_pypi_package
    environment:
        PYPI_INDEX_URL: https://test.pypi.org/simple
    requires: [publish_test_pypi]
  
  package_rpm:
     template: python/package_python
     steps:
        - install_utility: |
            yum install -y rpm-build redhat-rpm-config
            $BASE_PYTHON -m pip install -i https://test.pypi.org/simple invirtualenv==`meta get package.version`
        - package_code: |
            invirtualenv create_package rpm
        - install_package: rpm -ivh invirtualenv*.rpm
     requires: [verify_test_package]
  
  publish_prod_pypi:
    template: python/package_python
    environment:
      PUBLISH: True
    requires: [package_rpm]
