version: 4
shared:
  environment:
    PACKAGE_DIRECTORY: invirtualenv

jobs:
  validate_test:
    template: python/validate_unittest
    requires: [~commit, ~pr]

  validate_lint:
    template: python/validate_lint
    requires: [~commit, ~pr]

  validate_codestyle:
    template: python/validate_codestyle
    requires: [~commit, ~pr]

  # Take care of the fall positives this flags after the cleanup PR has been merged
  # validate_security:
  #   template: python/validate_security
  #   requires: [~commit, ~pr]

  generate_version:
    template: python/generate_version
    requires: [~commit]

  publish_test_pypi:
    template: python/package_python
    environment:
      PUBLISH: True
      TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
    requires: [validate_test, validate_lint, validate_codestyle, validate_security, generate_version]

  validate_test_install:
    # Install the published package in a virtualenv and run the tests on it.
    template: python/validate_unittest
    steps:
      - install_tox: |
        $BASE_PYTHON -m venv /tmp/functional_test
        PACKAGE_NAME="`$BASE_PYTHON setup.py --name`"
        PACKAGE_VERSION="`meta get package.version`"
        /tmp/functional_test/bin/pip install pytest
        /tmp/functional_test/bin/pip install --index-url=https://test.pypi.org/simple invirtualenv==$PACKAGE_VERSION
      - validate_code: |
        cd /tmp
        /tmp/functional_test/bin/pytest $SD_SOURCE_DIR/tests/  
        cd "$SD_SOURCE_DIR"
      - codecov: echo "No coverage for function tests"
    requires: [publish_test_pypi]
    
  publish_prod_pypi:
    template: python/package_python
    environment:
      PUBLISH: True
    requires: [validate_test_install]  
  
