#!/usr/bin/env python
# Copyright (c) 2016, Yahoo Inc.
# Copyrights licensed under the BSD License
# See the accompanying LICENSE.txt file for terms.

from __future__ import print_function
import logging
import os
from invirtualenv.deploy import build_deploy_virtualenv


if __name__ == '__main__':
    # logging.basicConfig(level=logging.DEBUG)
    if '/opt/python/bin' not in os.environ['PATH']:
        os.environ['PATH'] = '/opt/python/bin:' + os.environ['PATH']

    directory = build_deploy_virtualenv(update_existing=True)
    print('Created virtualenv: %s' % directory)